version: '3'

services:
  db:
    image: mysql
    container_name: mysql-db
    restart: always
    ports:
        - "3306:3306"
    environment:
      MYSQL_DATABASE: "medical_blind_spot"
      MYSQL_USER: "elice"
      MYSQL_PASSWORD: "1234"
      MYSQL_ROOT_PASSWORD: "1234"

  flask:
    build: .
    ports:
      - "80:80"
    links:
      - db:db
    command: gunicorn --bind 0.0.0.0:80 wsgi:app

  nginx:
    build: ./nginx
    ports:
      - "8080:8080"
    depends_on:
      - flask