version: '3'

services:
  db:
    image: mysql
    container_name: mysql-db
    restart: always
    ports:
        - "3306:3306"
    environment:
      MYSQL_DATABASE: "hello"
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "test"
      MYSQL_ROOT_PASSWORD: "root"

  flask:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db