version: '3'

services:
  db:
    image: mysql
    container_name: mysql-db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "medical_blind_spot"
      MYSQL_USER: "elice"
      MYSQL_PASSWORD: "1234"
      MYSQL_ROOT_PASSWORD: "1234"
    volumes:
      - dataonly

  flask:
    build: .
    ports:
      - "5000:5000"
    links:
      - db:db
    command: gunicorn --bind 0.0.0.0:5000 wsgi:app

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - flask